### ISSUE TITLE
Help, HTTP over TCP

### ISSUE THREAD

**Issue by ingnelson** [fangdingjun/sniproxy#6]
Hello @fangdingjun 

I am from America, is it  possible with your knowledge create a HTTP over TCP tunnel to bypass my isp provider , but any data the client need to transfer to the server should be via a new HTTP request ( encode64 ) then server decode the data  ? 
because my ISP provider blocks the upstream data via HTTP BODY.

It is difficul for me and i can not do it.
i did all the test to check the isp restrictions.

my telegram is : @Trader_Nelson

i will wait your reply.

**Comment by fangdingjun** [comment]
@ingnelson 

There are so many ways to bypass the ISP firewall,
example, shadowsocks, v2ray, http(s) proxy, ssh tunnel, openvpn, etc.

If you want to code it yourself, this [example](https://github.com/fangdingjun/wstunnel) may help you.

By the way, I think the best way is hire a lawer or switch to an other ISP.

**Comment by ingnelson** [comment]
@fangdingjun  I did a test to check the bytes size allow by the ISP provider by the http body : 

#on server:
`nc -l -n -p 80 | wc --bytes
`
#on client 
`for ((i=1;i<200;i++))  do dd if=/dev/zero bs=$i count=10; sleep 1 ; done | curl -s -X $'POST #blabla# HTTP/1.1\r\nX-Meta:' -T - -H 'Host:' -H 'User-Agent:' -H 'Accept:' -H 'Expect:' -H $'Trailer: 111\r\n ٌُُُُُُّّّّْْْْْْْْْْْْْْْْْْ\r\n\r\n' 172.245.22.211`

I found that the ISP block the connection  when the client upstream more than 50 bytes size.

someone created a android app (plugin ) + shadowsocks  . That app client create a tunnel to the server , but when the client send or transfer any data to the server , it send it using a new HTTP request encoding the data on the URL or http header (example: base64  ) then the server decode it . The client doesn't use the body to upstream any data , this way the ISP provider do not blocks the connection .

Look: 
![IMG_20200903_141246_483](https://user-images.githubusercontent.com/6626845/92162546-94f0d800-edef-11ea-8c3f-774cbf401380.jpg)

This is the packet I captured using TCPDUMP:
[quantumnica1.zip](https://github.com/fangdingjun/sniproxy/files/5170965/quantumnica1.zip)


Could you create a client and server like that , please ? 
Me and many people would thank you, because the guy who created that android app sell to us a monthly account to have internet free.

I would be happy to support you via BTC or PayPal. We really need your help to have free internet and not keep paying to that guy everytime

**Comment by fangdingjun** [comment]
Did you try shadowsocks or openvpn?

If that can not solve your problem, I can't give more help too. 

I'm sorry.
